### ISSUE TITLE
Not able to change font colors

### ISSUE THREAD

**Issue by ravensorb** [omsharp/BetterComments#1]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 1.1.9

### Description
Cannot change default colors.  It looks like your defaults assume a dark theme
![image](https://cloud.githubusercontent.com/assets/2222472/15634303/a6614ad0-258e-11e6-88c7-1f8514564c65.png))

So I am trying to change them to make it more useful for a light them.  I looked at your directions, however they do not seem to work
![Image](https://i.imgur.com/x6uUW6Q.png)

If you look at the image, there is no option for Text Editor and if I click on "All Text Tool Windows" I do not see any options to update Better Comments.  Please consider adding the settings directly into the better comments property screen.

**Comment by omsharp** [comment]
There is an issue with your Visual Studio not showing **Text Editor** in the settings combobox. Try to google why **Text Editor** is missing, and solve the issue first.

There should be a **Text Editor** option in the settings combobox, you can easily change the comment color there. Yours is missing for some reason that has nothing to do with the extension but with your installed instance of Visual Studio itself.

As for adding the color settings directly into the **Better Comments** options page, I didn't do it at first because I didn't want to reinvent the wheel. I thought better rely on VS for doing it than clutter my code with implementing a functionality that's already there. But still, I'll gladly consider it. I can't promise anything though.

Thanks for the feedback.

**Comment by omsharp** [comment]
I'll have to close this issue.

**Comment by ravensorb** [comment]
@omsharp this is a brand new install of VS2015 with Update 2 (I actually tested in on two brand new installs in virtual machines as I was testing other things as well).  Both behaved the same way.

Maybe you could add a detection for the current theme and at least set the colors based on that?

**Comment by omsharp** [comment]
@ravensorb the point is if you can't find **Text Editor** in the settings combobox, which I'm pretty sure its missing has nothing to do with **Better Comments**, then you have an issue with VS itself, you need that option to change many other classifications colors including _comment_. 

It is not just **Better Comments** that you can't change the colors of, without **Text Editor** settings you can't change many other code highlights like: _keyword_, _operator_, _types_, etc ... 

In the next version I'll consider setting the default colors based on the VS color theme.
